### ISSUE TITLE
Selecting "General Question" under Issues results in 404

### ISSUE THREAD

**Issue by vshorin** [1NCE-GmbH/1nce-iot-device-onboarding#9]
### Describe the issue

There seems to be an issue with the "issues" section of this repo 😃.
When "General Question" is clicked under the issues page https://github.com/1NCE-GmbH/1nce-iot-device-onboarding/issues/new/choose, the result is 404.
Not sure if this counts as a "Documentation Issue", but is not a bug in the code either.

### Links

https://github.com/1NCE-GmbH/1nce-iot-device-onboarding/issues/new/choose

**Comment by roberts-b** [comment]
Now issue is solved and customers can ask General Questions
